<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="footer-container">
    <!-- <div class="footer">
        <?php echo $block->getChildHtml() ?>
        <p class="bugs"><?php /* @escapeNotVerified */ echo __('Help Us Keep Magento Healthy') ?> - <a
            href="http://www.magentocommerce.com/bug-tracking"
            target="_blank"><strong><?php /* @escapeNotVerified */ echo __('Report All Bugs') ?></strong></a>
        </p>
        <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
    </div> -->
   <div class="anu">
        <p><strong>QUICK REFERENCE</strong></p>
        <ul>
        	<li>About Us</li>
        	<li>Placing a Limit Order</li>
        	<li>Dealer Application</li>
        	<li>IRA Rollovers</li>
        	<li>Selling Process</li>
        	<li>Store at CNT Depository</li>
        	<li>Track Your Package</li>
        	<li>Payment Instructions</li>
        	<li>Amazon Store</li>
        </ul>
    </div>

    <div class="anu2">
        <p><strong>QUICK REFERENCE</strong></p>
        <ul>
        	<li>About Us</li>
        	<li>Placing a Limit Order</li>
        	<li>Dealer Application</li>
        	<li>IRA Rollovers</li>
        	<li>Selling Process</li>
        	<li>Store at CNT Depository</li>
        	<li>Track Your Package</li>
        	<li>Payment Instructions</li>
        	<li>Amazon Store</li>
        </ul>
    </div>
</div>
